baseurl: '/'
permalink: pretty
title: 'datapand'
url: "https://www.datapand.com"

logo:
  mobile: "images/logo/datapand-logo.png"
  mobile_height: "32px"
  mobile_width: "64px"
  desktop: "images/logo/datapand-logo.png"
  desktop_height: "70px"
  desktop_width: "140px"

home: 
  limit_services: 3

collections:
  services:
    output: true
    sort_by: weight
  solutions:
    output: true
    sort_by: weight

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "solutions"
    values:
      layout: "solution"
  - scope:
      path: ""
      type: "technologies"
    values:
      layout: "technologies"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
